### ISSUE TITLE
python setup.py install error

### ISSUE THREAD

**Issue by liuxiaojun** [WojciechMula/pyahocorasick#6]
running install
running build
running build_ext
building 'ahocorasick' extension
clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Qunused-arguments -Qunused-arguments -DAHOCORASICK_UNICODE= -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pyahocorasick.c -o build/temp.macosx-10.10-x86_64-2.7/pyahocorasick.o
In file included from pyahocorasick.c:25:
./utils.c:90:69: warning: format specifies type 'int' but the argument has type 'ssize_t' (aka 'long')
      [-Wformat]
                PyErr_Format(PyExc_IndexError, "start index not in range %d..%d", min, max);
                                                                         ~~       ^~~
                                                                         %zd
./utils.c:90:74: warning: format specifies type 'int' but the argument has type 'ssize_t' (aka 'long')
      [-Wformat]
                PyErr_Format(PyExc_IndexError, "start index not in range %d..%d", min, max);
                                                                             ~~        ^~~
                                                                             %zd
./utils.c:113:67: warning: format specifies type 'int' but the argument has type 'ssize_t' (aka 'long')
      [-Wformat]
                PyErr_Format(PyExc_IndexError, "end index not in range %d..%d", min, max);
                                                                       ~~       ^~~
                                                                       %zd
./utils.c:113:72: warning: format specifies type 'int' but the argument has type 'ssize_t' (aka 'long')
      [-Wformat]
                PyErr_Format(PyExc_IndexError, "end index not in range %d..%d", min, max);
                                                                           ~~        ^~~
                                                                           %zd
In file included from pyahocorasick.c:29:
In file included from ./Automaton.c:948:
./Automaton_pickle.c:145:16: warning: cast to 'TrieNode *' (aka 'struct TrieNode *') from smaller integer
      type 'int' [-Wint-to-pointer-cast]
                dump->fail      = (TrieNode*)(NODEID(tmp)->id);
                                  ^
./Automaton_pickle.c:154:12: warning: cast to 'TrieNode *' (aka 'struct TrieNode *') from smaller integer
      type 'int' [-Wint-to-pointer-cast]
                arr[i] = (TrieNode*)(NODEID(child)->id);        // save id of child node
                         ^
pyahocorasick.c:42:1: error: unknown type name 'PyModuleDef'
PyModuleDef ahocorasick_module = {
^
pyahocorasick.c:43:2: error: use of undeclared identifier 'PyModuleDef_HEAD_INIT'
        PyModuleDef_HEAD_INIT,
        ^
pyahocorasick.c:59:11: warning: implicit declaration of function 'PyModule_Create' is invalid in C99
      [-Wimplicit-function-declaration]
        module = PyModule_Create(&ahocorasick_module);
                 ^
pyahocorasick.c:61:3: error: void function 'PyInit_ahocorasick' should not return a value [-Wreturn-type]
                return NULL;
                ^      ~~~~
pyahocorasick.c:65:3: error: void function 'PyInit_ahocorasick' should not return a value [-Wreturn-type]
                return NULL;
                ^      ~~~~
pyahocorasick.c:90:2: error: void function 'PyInit_ahocorasick' should not return a value [-Wreturn-type]
        return module;
        ^      ~~~~~~
7 warnings and 5 errors generated.
error: command 'clang' failed with exit status 1

**Comment by ZoaChou** [comment]
Same here.
On OS X 10.11.2 X86_64, Python 2.7.11.

**Comment by ZoaChou** [comment]
@liuxiaojun 
From the error message I del the three "return XXX" lines in pyahocorasick.c(lines:73,77,102),and install success now. I don't know why a void function has return,so you can try it. : )

**Comment by WojciechMula** [comment]
I'm going to merge that branch to the mainline, and then use your patch. Thanks for this.

**Comment by WojciechMula** [comment]
@ZoaChou I had fixed a few bugs in master and then rebased the port branch to the master. Then I wanted to include your changes (I simply picked a file from your commit https://github.com/WojciechMula/pyahocorasick/pull/18/commits/3f84fbe7a607697e698732b05e0be52e4cfd2d21), but unfortunately it breaks Python3 build. Python2 works OK.

Could you please verify if the current state of branch compiles on MacOS? As far I'm understand the problem reported by @liuxiaojun, now it should works.

**Comment by ZoaChou** [comment]
@WojciechMula I try to build on my MacOS again,it really breaks on python3.5.1 which I didn't test before.And I also try your latest commit,it works fine on my python2.7.11 now.You can close my pull request later,thanks.

**Comment by WojciechMula** [comment]
@ZoaChou Thank you very much for tests and your contribution.

**Comment by WojciechMula** [comment]
Closing, @ZaoChu has tested MacOS compilation.
